Financial-Times/n-content-body

scss/_body.scss, scss/_copyright.scss
stop polluting every p with a copyright message when printed
=> fix copyright

scss/_images.scss
This commit broke responsive images when attempting to shrink wrap content
=> Removes changes made in e938502

scss/_body.scss
I accidentally broke it yesterday
=> Bring back the agreed serification of body copy

.gitignore, Makefile, bower.json, n.Makefile, package.json
=> Build update

scss/_body.scss
@andygnewman because otherwise this
=> clear print notification

bower.json, main.scss
One of the few cases of it being a very easy update @andygnewman
=> next-sass-setup -> n-ui

scss/_related-box.scss
=> Hide related box image in core

scss/_tags.scss
sibling to this [PR](https://github.com/Financial-Times/next-article/pull/1541/files)
=> inline tags parent clear both

bower.json
@GlynnPhillips just a little update for you (:
=> updated n-ui to v3

scss/_mixins.scss
As was left out of n-ui-foundations
=> Add: nLists mixins to mixins

main.scss, scss/_big-number.scss, scss/_headings.scss, scss/_layout.scss, scss/_mixins.scss, scss/_pullquotes.scss, scss/_recommended.scss
* Update big number styles
* Refactor pull quotes a bit so they work inside layouts
* Initial prototype for layouting, which supports:
•	body and full-grid widths
•	nesting slots inside a layout equally divide the width
•	"wide" slots will be wider and also aligned center (TBD whether the centering is a good idea)
•	Components (pull quote, big number etc will be "inset" (read: floated) by default, and have to go into a layout box to be wide.
TODO:
Responsiveness of layouts
Griddiness of layouts?
=> WIP: initial layout work + big number

scss/_mixins.scss, scss/_pullquotes.scss
=> No square image on picture pullquote

scss/_blockquotes.scss, scss/_layout.scss, scss/_mixins.scss, scss/_pullquotes.scss
=> Inset picture pullquote, and add some clears to floated components

scss/_body.scss, scss/_headings.scss, scss/_recommended.scss
=> Fix recommended and ul spacing

main.scss, scss/_layout.scss
=> Override font for layouts and spacing tweak

scss/_headings.scss, scss/_layout.scss
=> Remove border from h1

scss/_recommended.scss
=> Use default link color for recommended

scss/_body.scss
=> Fix styling for big number in layouts

scss/_recommended.scss
Reverts Financial-Times/n-content-body#66
=> Revert "Use default link color for recommended"

scss/_layout.scss
=> Fix layout width on IE10

bower.json, scss/_blockquotes.scss
=> o-quote for blockquotes

scss/_layout.scss
=> Layout tweaks again

scss/_pullquotes.scss
=> Update font size/line height for pullquotes

scss/_images.scss
=> Update image caption size/spacing

scss/_headings.scss
=> Use origami headling level mixins

scss/_pullquotes.scss
=> Lose uppercase on pull quote

bower.json, scss/_mixins.scss
Follows the [migration guide](https://github.com/Financial-Times/n-ui-foundations/issues/34#issuecomment-341787777)
=> Upgrade n-ui-foundations to v3 beta

scss/layout/_timeline.scss
=> modify margin

scss/layout/_timeline.scss
modify oGolorsGetPaletteColor('black') to getColor('black') 
🐿 v2.5.16
=> fix missing timeline elements

scss/layout/_main.scss
🐿 v2.7.0
[Trello](https://trello.com/c/nqLxtTDf/21-see-if-we-can-make-the-hacky-line-invisible-on-next-but-appear-on-the-app)
=> Hide Méthode hacky horizontal rules in layoutsets

.circleci/config.yml, circle.yml
=> Circle2 migration

bower.json, scss/_big-number.scss, scss/_blockquotes.scss, scss/_body.scss, scss/_headings.scss, scss/_images.scss, scss/_mixins.scss, scss/_print.scss, scss/_pullquotes.scss, scss/_recommended.scss, scss/_related-box.scss, scss/layout/_aside.scss, scss/layout/_card.scss, scss/layout/_main.scss, scss/layout/_timeline.scss, test/integration/compile-main.test.js, test/integration/entry-file.scss
Upgrade origami components and `n-ui-foundations` as part of the breaking change. This is mostly just swapping mixins to the new names.
=> Origami Upgrade

bower.json, scss/_blockquotes.scss, scss/_body.scss, scss/_pullquotes.scss, scss/_recommended.scss, scss/layout/_main.scss, scss/layout/_timeline.scss
Being able to see the changes in this there were a few bugs. This fixes
them so that it matches how it used to appear in production. 🐿 v2.12.5
=> Style tweaks after integration with next-article

bower.json
- Pulls in a new heading style for articles (h4, features xhead)
- Increases bottom margin of article headings slightly.
=> Bump the version of o-editorial-typography and o-editorial-layout

.circleci/config.yml, package.json
This upgrades the n-content-body component to use NPM 7 as part of the migration away from bower.
=> Upgrade to NPM7

.circleci/config.yml, package.json
Upgrade to Node 16
[https://financialtimes.atlassian.net/browse/CI-1068](https://financialtimes.atlassian.net/browse/CI-1068)
=> [CI-1068] Upgrade to node 16
