Financial-Times/n-content-body

scss/_related-box.scss

@i-like-robots 
To address promobox headline text overflowing its container (in particular when an article is prepared for printing, because the full link href is included).
Although it looks like this problem is only really on IE at the moment, I think that this fix will also prevent unusually long words from overflowing on other browsers, also.
Jira issue [here](https://jira.ft.com/browse/NFT-243).

break overlong promo-box text

---

scss/_images.scss

Previously the if an image had a long caption it was forcing the width
of the `<figure>` to its width rather than the width of the image.

Updates the style of images with long captions

---

scss/_mixins.scss

Now when the button displays "Show less" the icon will also switch to an
up arrow.

Switches to an up arrow icon when box is expanded

---

scss/_tags.scss

Resisting the temptation to make this more robust, in favour of shipping a fix

Bump padding to stop topic-name & button overlap

---

scss/_mixins.scss

The 3 things that still call this mixin all fall into the `else`, so we can remove the conditionals altogether.
(Less of a yak shave than removing it completely.)

Simplify the mega-old nListsItemLink mixin a bit

---

scss/_mixins.scss

(so we don't load an extra font for them)

Use Metric for promo box headers

---

scss/_layout.scss

Background for layouts

---

scss/_layout.scss

🐿2.5.10
Not sure why 1 1 1px worked but ¯\_(ツ)_/¯

Allow full width headings and elements in layouts

---

scss/_layout.scss

halve the opacity of n-content-layout background

---

main.scss
scss/layout/_aside.scss
scss/layout/_card.scss
scss/layout/_default.scss
scss/layout/_main.scss
scss/layout/_widths.scss

🐿2.5.10
* By default, layouts have no background
* [data-layout-name="aside"], [data-layout-name="card"] get a background
* add [data-layout-width="inset-left"]
* [data-slot-width="wide"]
* All the data-layout-* apply to both layouts and layoutsets

Make layout widths and names work

---

scss/layout/_aside.scss
scss/layout/_card.scss
scss/layout/_timeline.scss

Bit warmer, less hacky
before 
after

use non-transparent bg for cards and asides

---

scss/_mixins.scss
scss/layout/_widths.scss

- added styles to support otable large layout option: inset-right
- trello card: https://trello.com/c/xPAfiAf5/18-set-large-screen-layout
- related PR: https://github.com/Financial-Times/next-es-interface/pull/1313
- this change is non breaking, fully backward compatible
🐿 v2.12.0

added support for otable large layout

---

scss/_body.scss

AMP, App, ft.com are now using the o-table component. It seems that there are no other application inside ft.com that are using this styles directly from n-content-body so it should be safe to delete them.
Reference to [trello ticket](https://trello.com/c/4tgOPHbC/31-pre-live-remove-data-styles-from-n-content-body)

feat: remove old data-table styles cause we are using o-table now

---

scss/layout/_widths.scss

- the padding 40px is needed to handle the feedback button
- said button size is set in px in n-feedback, so it does make sense to do the same here
related to PR: https://github.com/Financial-Times/next-es-interface/pull/1315
🐿 v2.12.0

added support for otable full-bleed option

---

scss/layout/_widths.scss

🐿 v2.12.0
- fullbleed tables did not render properly on smaller devices
- do not bleed over the grid on size < L, just stay stay in the parent container boundaries
- added media queries sizes > L to enable  fullbleed
size < L 
size > L

media queries for otable fullbleed option

---

scss/_body.scss

Left align captions and add padding if the table goes over the standard layout width.
Also add heading styles inside captions.
---
This should be reviewed in conjunction with https://github.com/Financial-Times/next-es-interface/pull/1359, where we move styling out of `next-es-interface` into here.

Apply styles to table captions

---

scss/_headings.scss

Currently [breaks](https://circleci.com/gh/Financial-Times/next-article/18540) when building `_body.scss` because `nContentHeading6` does not exist. From the changes of https://github.com/Financial-Times/n-content-body/pull/107.
`o-typography` says [heading level 6 is for internal/whitelabel use](https://github.com/Financial-Times/o-typography/blob/9dacce1dd9f6256fcad21c1ffc36ce8cce47f936/src/scss/use-cases/_headings.scss#L51-L55), but I think that's fine here. I don't think it will be used in practice, but I don't see anything wrong with adding it here for completeness.
Also created this issue to prevent this from happening in future: https://github.com/Financial-Times/n-content-body/issues/108

Add nContentHeading6 styles

---

scss/_body.scss
scss/_headings.scss

Previously https://github.com/Financial-Times/n-content-body/pull/109, didn't fix the issue. The build still [breaks](https://circleci.com/gh/Financial-Times/next-article/18541) when compiling `oTypographyHeadingLevel6`, so reverting that PR, and using `h4` styles for `.n-content-body__caption--h5` instead 🤞

Remove reference to `nContentHeading6` in captions

---

scss/_body.scss

Use `nContentHeading5` for `h6` as that is the [lowest heading style supported](https://github.com/Financial-Times/n-content-body/pull/110).
Should have gone into https://github.com/Financial-Times/n-content-body/pull/107, but was left out 😬 
It would be passed through: https://github.com/Financial-Times/next-es-interface/blob/170b9e664fe913d0529586d252289f6af8cb7265/server/transformers/plugins/article/concerns/transform-data-tables.js#L90

Add missing h6 style

---

scss/_big-number.scss
secret-squirrel.js

Big numbers in the new UPP schema do not allow for paragraph tags (which
kind of makes sense - the `<p>` tags are a little redundant here and I think a hangover from Methode).
The current styles however look a bit odd without paragraph tags - so these
changes make it look okay with/without.
Before:
After:
🐿2.5.10

Make big numbers without paragraphs look correct.

---

Makefile
package.json
test/integration/compile-main.test.js

If `n-content-body` has `scss` compilation problems, it's not caught until downstream, when it is included eg, `next-article`. This fix adds an integration test to compile `main.scss` when testing on CircleCI, so the compilation errors can be caught in this repo before problems get shipped out.
Example of failing build: https://circleci.com/gh/Financial-Times/n-content-body/1435
Fixes https://github.com/Financial-Times/n-content-body/issues/108

Add integration test

---

scss/_blockquotes.scss

`oQuoteStandardIcon()` was deprecated some time ago and is no longer
used so remove it from here so that we stop getting warnings on build.

Remove deprecated oQuote call

---

package.json

node v8 end of life is 2019-12-31. As n-content-body only uses node
locally, remove the node version from package.json
https://nodejs.org/en/about/releases/

Remove node version from package.json

---

scss/_body.scss

This was being set in next-article to override what was set here. Moving
this into n-content-body will let us use the same sizes in other
applications. 🐿 v2.12.5

Use paragraph sizes from next-article

---

scss/_body.scss

Fixes typo that used `oTypographySans` mixin instead of `oTypographySerif`.
See [incident report](https://github.com/Financial-Times/next-bugs/issues/253).

Fix wrong font on body text - use serif on paragraphs

---

README.md
bower.json

Jira card: https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-84.
I have `bower link`ed this component and run locally on `next-article` (https://www.ft.com/kitchenus-sinkus-articlus). `next-article` is a bit fiddly as it imports `n-ui-foundations` from several different Bower dependencies, as well as importing it directly in its own `bower.json`.
Therefore to get it working, I had to apply the changes required in the [`n-ui-foundations` Migration guide v5 to v6](https://github.com/Financial-Times/n-ui-foundations#user-content-v5-to-v6) (e.g. `@include oGridContainer($grid-mode: 'snappy');`) to a couple of the SASS files of my locally-running instance (`client/components/grid/_helpers.scss` and `client/components/grid/package.scss`). …

Upgrade n-ui-foundations ^4.0.0 -> ^6.0.0

---

bower.json
scss/_blockquotes.scss

Designed by Josh in the Content Innovation Team.
Background: https://github.com/Financial-Times/o-quote/issues/51
demo: https://www.ft.com/__origami/service/build/v2/demos/o-quote@4.1.2/editorial?brand=master

Use new editorial quote style.

---

bower.json
scss/_body.scss
scss/_headings.scss
scss/layout/_main.scss

**motivation**
Multiple teams/projects create article layouts. Customer products,
including `next-article` and `ft-app`; Spark for article preview;
interactive graphics.
Not all teams can depend on `n-content-body`, and trying to [may be
complex](https://github.com/Financial-Times/ft-app/blob/c6d89334b325edc2dfa625b878c19ba915d0fa4a/lib/css/article/main.scss#L74).
`o-editorial-layout` replaces parts of `n-content-body` for other
teams to use. However its difficult to update article markup for
existing `n-content-body` users. To make sure users of `n-content-body`
and `o-editorial-layout` are aligned, this PR uses `o-editorial-layout`
within the existing `n-content-body` interface.
In the future, replacing more `n-content-body` content with individual
components would allow more reuse. …

Use the `o-editorial-layout` component.

---

README.md
scss/_video.scss

[Ticket.](https://financialtimes.atlassian.net/browse/CI-470)
YouTube videos are to be used with different widths in different places, so this PR extracts the width from the component so that we can set it where we use the component, giving greater flexibility.
To test:
- Navigate to a [live blog v2 with a YouTube video](https://local.ft.com:5050/content/b47a8dd0-81dc-4136-807c-c071c75c8fe2#post-750889ba-d5b6-41fb-88aa-d35aca642b79) (turn liveBlogsV2 on in toggler).
- Assert that YouTube videos are the full width of the article.
Needs to go live at the same time as this [PR](https://github.com/Financial-Times/next-article/pull/4122).

CI-470 Extract width from video.scss

---

.circleci/config.yml

In response to the endorsed proposal: [TGG: Address offensive and objectionable technology terms](https://docs.google.com/document/d/1v6z7_NkLFeYAFotTYB8C1OguO5iMHHLpAOv_yG5EKHI
).
Once this is merged I'll do the rest of the steps documented here:
https://github.com/Financial-Times/next/wiki/Migrating-apps-to-use-main-branch-(instead-of-master)

CI-475: Rename master to main

---

bower.json

This will increase the bottom margin of h2 and h3 editorial headings.
Requested by Kevin (Editorial Creative Director) and Mus (Head of
Editorial Platforms).
https://github.com/Financial-Times/o-editorial-layout/pull/53

Require the latest version of o-editorial-layout

---

scss/_print.scss
scss/_related-box.scss

These promo boxes are now removed in ES-interface so the styles shouldn't be used anymore
https://github.com/Financial-Times/next-es-interface/pull/1645

Remove promo box styles that should no longer be used

---

.circleci/config.yml

The snyk step is currently preventing this component from publishing as it errors with `Unexpected token *`
We can't seem to figure out why this is happening as it works locally.
This component doesn't have any dependencies anyway that would be tested by snyk and I don't imagine any being added in the future due to what the component is used for so removing this step should have no impact.

Remove the snyk step from CircleCI

---

scss/_headings.scss

This was added a long time ago and I don't think the situation it was added for exists any longer regarding running into floats.
This style is not added to any other heading level which can be used in the same context as a heading level 2 so I am going to try removing it and monitor the impact.
By removing this it will allow us to use `scroll-margin-top` to offset the scroll positions of headings so that when we link to headings using # in the url they are not hidden behind the sticky navigation

Remove overflow hidden on heading level 2

---

bower.json
scss/_headings.scss

Adding scroll-margin-top means that when someone uses a url with a # in it that links to a specific heading
that heading wont be hidden behind the sticky navigation at the top of the page
**Screenshot before change**
The below image shows the heading behind the sticky navigation when the user navigates to a url with a hash jump link in it
**Screenshot after change**
The below image shows the heading is no longer behind the sticky navigation when the user navigates to a url with a hash jump link in it
**Limitations**
This wont work in some much older browsers such as IE11 (hopefully being dropped soon 🤞) but it will just fall back to the behaviour before this change. This feels acceptable in those minor cases.

Prevent linked to headings from being hidden by sticky nav

---

scss/_blockquotes.scss
scss/_body.scss
scss/_headings.scss

As a result of changing the components from bower to NPM, we needed to update the paths to correct import the stylesheets. Without it, trying to build this in other projects was throwing the following error: Can't find stylesheet to import.

Update import paths to have @financial-times

---

scss/_images.scss

Currently on ft.com we don't set a height attribute on body images.
With the cp-content-pipeline, we plan to add a width/height attribute, so that the appropriate space is reserved (which is what the app currently does).
For this to work, we need to set `height: auto` in the CSS for images, so that the rendered aspect ratio remains the same.
This should have no impact on current image rendering, as we're not setting `height` on the image tag.

Add height: auto to images

---

scss/_recommended.scss

Updates the .n-content-recommended styles for `.n-content-recommended--single-story` and `.n-content-recommended__title` to reduce duplication between next-article and the app when the [cp-content-pipeline UI](https://github.com/Financial-Times/cp-content-pipeline/tree/main/packages/ui) gets implemented. 
These styles are already present in [next-article](https://github.com/Financial-Times/next-article/blob/main/client/components/article/_main.scss)

Update the n-content-recommended styles

---

scss/layout/_widths.scss

[Ticket](https://financialtimes.atlassian.net/browse/CI-1690) 
Moved [this](https://github.com/Financial-Times/n-clip/blob/main/client/main.scss#L10) style to here. 
After this is merged, merge these in order:
- next-article: a PR bumping up n-content-body, to include the new styles
- ft-app: a PR bumping up n-content-body, to include the new styles
- n-clip: [PR](https://github.com/Financial-Times/n-clip/pull/29) replacing o-clip__container--* with these n-content-layout__container* CSS class names in the template, removing unused styles o-clip__container--*
- next-es-interface: a PR bumping up n-clip, to include the new HTML
Phase 2: (Only do this after the above is released and tested to ensure backward compatibility)
- next-article: a PR bumping up n-clip, to remove the …

refactor: move style from n-clip to n-content-body
